name: mapbox_geocoding
description: Mapbox Geocoding API library in order to make forward and reverse geocoding.
version: 0.1.3
author: 'Berkay Oru√ß <berkayoruc0@gmail.com>'
homepage: https://github.com/hexa-apps/mapbox_geocoding/

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0+4

dev_dependencies:
